[package]
name = "variant-name"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]

[dependencies]
variant-name-derive = { path = "variant-name-derive" }
variant-name-trait = { path = "variant-name-trait" }

